version: '3.3'

services:
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  app:
    build:  
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
      - |
        ROCKET_DATABASES={
          postgres={url=postgres://postgres:postgres@postgres/app_db},
          redis={url=redis://redis:6379}
        }
      - HOST=http://127.0.0.1:8000
    volumes: 
      - prod_config:/config
      - prod_data:/data
      - postgres_data_prod:/app/data

volumes:
  prod_config:
  prod_data:
  postgres_data_prod: