version: '3.3'

services:
  postgres:
    image: postgres:latest
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: redis:latest

  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ports:
      - 8000:8000