version: '3.3'

services:
  postgres:
    environment:
      - POSTGRES_USER=postgres_dev
      - POSTGRES_PASSWORD=postgres_dev
      - POSTGRES_DB=app_db_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  app:
    build:  
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres_dev:postgres_dev@postgres/app_db_dev
      - |
        ROCKET_DATABASES={
          postgres={url=postgres://postgres_dev:postgres_dev@postgres/app_db_dev},
          redis={url=redis://redis:6379}
        }
      - HOST=http://127.0.0.1:8000
    volumes: 
      - dev_config:/config
      - dev_data:/data
      - cargo_cache:/usr/local/cargo/registry 

volumes:
  dev_config:
  dev_data:
  cargo_cache:
  postgres_data_dev: