// Generated by diesel_ext
use super::schema::*;
use chrono::NaiveDateTime;

// #[derive(serde::Serialize, serde::Deserialize, diesel::Queryable, Associations)]
#[derive(serde::Serialize, serde::Deserialize, diesel::Queryable)]
pub struct Crate {
    pub id: i32,
    pub rustaceans_id: i32,
    pub code: String,
    pub name: String,
    pub version: String,
    pub description: Option<String>,
    pub created_at: NaiveDateTime,
}

#[derive(serde::Deserialize, diesel::Queryable, Insertable)]
#[diesel(table_name = crates)]
pub struct NewCrate {
    pub rustaceans_id: i32,
    pub code: String,
    pub name: String,
    pub version: String,
    pub description: Option<String>,
}

#[derive(serde::Serialize, serde::Deserialize, diesel::Queryable)]
pub struct Rustacean {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub created_at: NaiveDateTime,
}

#[derive(serde::Deserialize, diesel::Queryable, Insertable)]
#[diesel(table_name = rustaceans)]
pub struct NewRustacean {
    pub name: String,
    pub email: String,
}
